package ac.at.tuwien.mt.monitoring.internal;

import ac.at.tuwien.mt.model.datacontract.DataContract;
import ac.at.tuwien.mt.model.thing.Thing;
import ac.at.tuwien.mt.model.thing.ThingId;
import ac.at.tuwien.mt.model.thing.message.Attribute;
import ac.at.tuwien.mt.model.thing.message.DataType;
import ac.at.tuwien.mt.model.thing.message.MetaModel;
import ac.at.tuwien.mt.model.thing.message.Property;

public final class ThingProvider {

	public static DataContract getDataContract(String thingId) {
		DataContract dc = new DataContract();
		dc.setMonitoring(true);
		dc.getThingIds().add(new ThingId(thingId));
		return dc;
	}

	public static Thing getThing1(String thingId) {
		Thing thing = new Thing();
		thing.setThingId(thingId);
		thing.getQos().setFrequency(100);

		Attribute attribute1 = new Attribute();
		attribute1.setDataType(DataType.STRING);
		attribute1.setName("thingId");
		Property property = new Property();
		property.setIdentifier(true);
		attribute1.setProperty(property);

		Attribute attribute2 = new Attribute();
		attribute2.setDataType(DataType.DOUBLE);
		attribute2.setName("temperature");

		Attribute attribute3 = new Attribute();
		attribute3.setDataType(DataType.STRING);
		attribute3.setName("scale");

		Attribute attribute4 = new Attribute();
		attribute4.setDataType(DataType.DATE);
		attribute4.setName("recordingTime");
		Property property4 = new Property();
		property4.setIdentifier(false);
		property4.setRecordingDate(true);
		property4.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
		attribute4.setProperty(property4);

		MetaModel model1 = new MetaModel();
		model1.getAttributes().add(attribute1);
		model1.getAttributes().add(attribute2);
		model1.getAttributes().add(attribute3);
		model1.getAttributes().add(attribute4);

		thing.setMetaModel(model1);

		return thing;

	}

	public static Thing getThing3(String thingId) {
		Thing thing = new Thing();
		thing.setThingId(thingId);
		thing.getQos().setFrequency(100);

		MetaModel mm = new MetaModel();

		Attribute a0 = new Attribute();
		a0.setDataType(DataType.STRING);
		a0.setName("c0");
		mm.getAttributes().add(a0);
		Attribute a1 = new Attribute();
		a1.setDataType(DataType.STRING);
		a1.setName("c1");
		mm.getAttributes().add(a1);
		Attribute a2 = new Attribute();
		a2.setDataType(DataType.STRING);
		a2.setName("c2");
		mm.getAttributes().add(a2);
		Attribute a3 = new Attribute();
		a3.setDataType(DataType.STRING);
		a3.setName("c3");
		mm.getAttributes().add(a3);
		Attribute a4 = new Attribute();
		a4.setDataType(DataType.STRING);
		a4.setName("c4");
		mm.getAttributes().add(a4);
		Attribute a5 = new Attribute();
		a5.setDataType(DataType.STRING);
		a5.setName("c5");
		mm.getAttributes().add(a5);
		Attribute a6 = new Attribute();
		a6.setDataType(DataType.STRING);
		a6.setName("c6");
		mm.getAttributes().add(a6);
		Attribute a7 = new Attribute();
		a7.setDataType(DataType.STRING);
		a7.setName("c7");
		mm.getAttributes().add(a7);
		Attribute a8 = new Attribute();
		a8.setDataType(DataType.STRING);
		a8.setName("c8");
		mm.getAttributes().add(a8);
		Attribute a9 = new Attribute();
		a9.setDataType(DataType.STRING);
		a9.setName("c9");
		mm.getAttributes().add(a9);
		Attribute a10 = new Attribute();
		a10.setDataType(DataType.STRING);
		a10.setName("c10");
		mm.getAttributes().add(a10);
		Attribute a11 = new Attribute();
		a11.setDataType(DataType.STRING);
		a11.setName("c11");
		mm.getAttributes().add(a11);
		Attribute a12 = new Attribute();
		a12.setDataType(DataType.STRING);
		a12.setName("c12");
		mm.getAttributes().add(a12);
		Attribute a13 = new Attribute();
		a13.setDataType(DataType.STRING);
		a13.setName("c13");
		mm.getAttributes().add(a13);
		Attribute a14 = new Attribute();
		a14.setDataType(DataType.STRING);
		a14.setName("c14");
		mm.getAttributes().add(a14);
		Attribute a15 = new Attribute();
		a15.setDataType(DataType.STRING);
		a15.setName("c15");
		mm.getAttributes().add(a15);
		Attribute a16 = new Attribute();
		a16.setDataType(DataType.STRING);
		a16.setName("c16");
		mm.getAttributes().add(a16);
		Attribute a17 = new Attribute();
		a17.setDataType(DataType.STRING);
		a17.setName("c17");
		mm.getAttributes().add(a17);
		Attribute a18 = new Attribute();
		a18.setDataType(DataType.STRING);
		a18.setName("c18");
		mm.getAttributes().add(a18);
		Attribute a19 = new Attribute();
		a19.setDataType(DataType.STRING);
		a19.setName("c19");
		mm.getAttributes().add(a19);
		Attribute a20 = new Attribute();
		a20.setDataType(DataType.STRING);
		a20.setName("c20");
		mm.getAttributes().add(a20);
		Attribute a21 = new Attribute();
		a21.setDataType(DataType.STRING);
		a21.setName("c21");
		mm.getAttributes().add(a21);
		Attribute a22 = new Attribute();
		a22.setDataType(DataType.STRING);
		a22.setName("c22");
		mm.getAttributes().add(a22);
		Attribute a23 = new Attribute();
		a23.setDataType(DataType.STRING);
		a23.setName("c23");
		mm.getAttributes().add(a23);
		Attribute a24 = new Attribute();
		a24.setDataType(DataType.STRING);
		a24.setName("c24");
		mm.getAttributes().add(a24);
		Attribute a25 = new Attribute();
		a25.setDataType(DataType.STRING);
		a25.setName("c25");
		mm.getAttributes().add(a25);
		Attribute a26 = new Attribute();
		a26.setDataType(DataType.STRING);
		a26.setName("c26");
		mm.getAttributes().add(a26);
		Attribute a27 = new Attribute();
		a27.setDataType(DataType.STRING);
		a27.setName("c27");
		mm.getAttributes().add(a27);
		Attribute a28 = new Attribute();
		a28.setDataType(DataType.STRING);
		a28.setName("c28");
		mm.getAttributes().add(a28);
		Attribute a29 = new Attribute();
		a29.setDataType(DataType.STRING);
		a29.setName("c29");
		mm.getAttributes().add(a29);
		Attribute a30 = new Attribute();
		a30.setDataType(DataType.STRING);
		a30.setName("c30");
		mm.getAttributes().add(a30);
		Attribute a31 = new Attribute();
		a31.setDataType(DataType.STRING);
		a31.setName("c31");
		mm.getAttributes().add(a31);
		Attribute a32 = new Attribute();
		a32.setDataType(DataType.STRING);
		a32.setName("c32");
		mm.getAttributes().add(a32);
		Attribute a33 = new Attribute();
		a33.setDataType(DataType.STRING);
		a33.setName("c33");
		mm.getAttributes().add(a33);
		Attribute a34 = new Attribute();
		a34.setDataType(DataType.STRING);
		a34.setName("c34");
		mm.getAttributes().add(a34);
		Attribute a35 = new Attribute();
		a35.setDataType(DataType.STRING);
		a35.setName("c35");
		mm.getAttributes().add(a35);
		Attribute a36 = new Attribute();
		a36.setDataType(DataType.STRING);
		a36.setName("c36");
		mm.getAttributes().add(a36);
		Attribute a37 = new Attribute();
		a37.setDataType(DataType.STRING);
		a37.setName("c37");
		mm.getAttributes().add(a37);
		Attribute a38 = new Attribute();
		a38.setDataType(DataType.STRING);
		a38.setName("c38");
		mm.getAttributes().add(a38);
		Attribute a39 = new Attribute();
		a39.setDataType(DataType.STRING);
		a39.setName("c39");
		mm.getAttributes().add(a39);
		Attribute a40 = new Attribute();
		a40.setDataType(DataType.STRING);
		a40.setName("c40");
		mm.getAttributes().add(a40);
		Attribute a41 = new Attribute();
		a41.setDataType(DataType.STRING);
		a41.setName("c41");
		mm.getAttributes().add(a41);
		Attribute a42 = new Attribute();
		a42.setDataType(DataType.STRING);
		a42.setName("c42");
		mm.getAttributes().add(a42);
		Attribute a43 = new Attribute();
		a43.setDataType(DataType.STRING);
		a43.setName("c43");
		mm.getAttributes().add(a43);
		Attribute a44 = new Attribute();
		a44.setDataType(DataType.STRING);
		a44.setName("c44");
		mm.getAttributes().add(a44);
		Attribute a45 = new Attribute();
		a45.setDataType(DataType.STRING);
		a45.setName("c45");
		mm.getAttributes().add(a45);
		Attribute a46 = new Attribute();
		a46.setDataType(DataType.STRING);
		a46.setName("c46");
		mm.getAttributes().add(a46);
		Attribute a47 = new Attribute();
		a47.setDataType(DataType.STRING);
		a47.setName("c47");
		mm.getAttributes().add(a47);
		Attribute a48 = new Attribute();
		a48.setDataType(DataType.STRING);
		a48.setName("c48");
		mm.getAttributes().add(a48);
		Attribute a49 = new Attribute();
		a49.setDataType(DataType.STRING);
		a49.setName("c49");
		mm.getAttributes().add(a49);
		Attribute a50 = new Attribute();
		a50.setDataType(DataType.STRING);
		a50.setName("c50");
		mm.getAttributes().add(a50);
		Attribute a51 = new Attribute();
		a51.setDataType(DataType.STRING);
		a51.setName("c51");
		mm.getAttributes().add(a51);
		Attribute a52 = new Attribute();
		a52.setDataType(DataType.STRING);
		a52.setName("c52");
		mm.getAttributes().add(a52);
		Attribute a53 = new Attribute();
		a53.setDataType(DataType.STRING);
		a53.setName("c53");
		mm.getAttributes().add(a53);
		Attribute a54 = new Attribute();
		a54.setDataType(DataType.STRING);
		a54.setName("c54");
		mm.getAttributes().add(a54);
		Attribute a55 = new Attribute();
		a55.setDataType(DataType.STRING);
		a55.setName("c55");
		mm.getAttributes().add(a55);
		Attribute a56 = new Attribute();
		a56.setDataType(DataType.STRING);
		a56.setName("c56");
		mm.getAttributes().add(a56);
		Attribute a57 = new Attribute();
		a57.setDataType(DataType.STRING);
		a57.setName("c57");
		mm.getAttributes().add(a57);
		Attribute a58 = new Attribute();
		a58.setDataType(DataType.STRING);
		a58.setName("c58");
		mm.getAttributes().add(a58);
		Attribute a59 = new Attribute();
		a59.setDataType(DataType.STRING);
		a59.setName("c59");
		mm.getAttributes().add(a59);
		Attribute a60 = new Attribute();
		a60.setDataType(DataType.STRING);
		a60.setName("c60");
		mm.getAttributes().add(a60);
		Attribute a61 = new Attribute();
		a61.setDataType(DataType.STRING);
		a61.setName("c61");
		mm.getAttributes().add(a61);
		Attribute a62 = new Attribute();
		a62.setDataType(DataType.STRING);
		a62.setName("c62");
		mm.getAttributes().add(a62);
		Attribute a63 = new Attribute();
		a63.setDataType(DataType.STRING);
		a63.setName("c63");
		mm.getAttributes().add(a63);
		Attribute a64 = new Attribute();
		a64.setDataType(DataType.STRING);
		a64.setName("c64");
		mm.getAttributes().add(a64);
		Attribute a65 = new Attribute();
		a65.setDataType(DataType.STRING);
		a65.setName("c65");
		mm.getAttributes().add(a65);
		Attribute a66 = new Attribute();
		a66.setDataType(DataType.STRING);
		a66.setName("c66");
		mm.getAttributes().add(a66);
		Attribute a67 = new Attribute();
		a67.setDataType(DataType.STRING);
		a67.setName("c67");
		mm.getAttributes().add(a67);
		Attribute a68 = new Attribute();
		a68.setDataType(DataType.STRING);
		a68.setName("c68");
		mm.getAttributes().add(a68);
		Attribute a69 = new Attribute();
		a69.setDataType(DataType.STRING);
		a69.setName("c69");
		mm.getAttributes().add(a69);
		Attribute a70 = new Attribute();
		a70.setDataType(DataType.STRING);
		a70.setName("c70");
		mm.getAttributes().add(a70);
		Attribute a71 = new Attribute();
		a71.setDataType(DataType.STRING);
		a71.setName("c71");
		mm.getAttributes().add(a71);
		Attribute a72 = new Attribute();
		a72.setDataType(DataType.STRING);
		a72.setName("c72");
		mm.getAttributes().add(a72);
		Attribute a73 = new Attribute();
		a73.setDataType(DataType.STRING);
		a73.setName("c73");
		mm.getAttributes().add(a73);
		Attribute a74 = new Attribute();
		a74.setDataType(DataType.STRING);
		a74.setName("c74");
		mm.getAttributes().add(a74);
		Attribute a75 = new Attribute();
		a75.setDataType(DataType.STRING);
		a75.setName("c75");
		mm.getAttributes().add(a75);
		Attribute a76 = new Attribute();
		a76.setDataType(DataType.STRING);
		a76.setName("c76");
		mm.getAttributes().add(a76);
		Attribute a77 = new Attribute();
		a77.setDataType(DataType.STRING);
		a77.setName("c77");
		mm.getAttributes().add(a77);
		Attribute a78 = new Attribute();
		a78.setDataType(DataType.STRING);
		a78.setName("c78");
		mm.getAttributes().add(a78);
		Attribute a79 = new Attribute();
		a79.setDataType(DataType.STRING);
		a79.setName("c79");
		mm.getAttributes().add(a79);
		Attribute a80 = new Attribute();
		a80.setDataType(DataType.STRING);
		a80.setName("c80");
		mm.getAttributes().add(a80);
		Attribute a81 = new Attribute();
		a81.setDataType(DataType.STRING);
		a81.setName("c81");
		mm.getAttributes().add(a81);
		Attribute a82 = new Attribute();
		a82.setDataType(DataType.STRING);
		a82.setName("c82");
		mm.getAttributes().add(a82);
		Attribute a83 = new Attribute();
		a83.setDataType(DataType.STRING);
		a83.setName("c83");
		mm.getAttributes().add(a83);
		Attribute a84 = new Attribute();
		a84.setDataType(DataType.STRING);
		a84.setName("c84");
		mm.getAttributes().add(a84);
		Attribute a85 = new Attribute();
		a85.setDataType(DataType.STRING);
		a85.setName("c85");
		mm.getAttributes().add(a85);
		Attribute a86 = new Attribute();
		a86.setDataType(DataType.STRING);
		a86.setName("c86");
		mm.getAttributes().add(a86);
		Attribute a87 = new Attribute();
		a87.setDataType(DataType.STRING);
		a87.setName("c87");
		mm.getAttributes().add(a87);
		Attribute a88 = new Attribute();
		a88.setDataType(DataType.STRING);
		a88.setName("c88");
		mm.getAttributes().add(a88);
		Attribute a89 = new Attribute();
		a89.setDataType(DataType.STRING);
		a89.setName("c89");
		mm.getAttributes().add(a89);
		Attribute a90 = new Attribute();
		a90.setDataType(DataType.STRING);
		a90.setName("c90");
		mm.getAttributes().add(a90);
		Attribute a91 = new Attribute();
		a91.setDataType(DataType.STRING);
		a91.setName("c91");
		mm.getAttributes().add(a91);
		Attribute a92 = new Attribute();
		a92.setDataType(DataType.STRING);
		a92.setName("c92");
		mm.getAttributes().add(a92);
		Attribute a93 = new Attribute();
		a93.setDataType(DataType.STRING);
		a93.setName("c93");
		mm.getAttributes().add(a93);
		Attribute a94 = new Attribute();
		a94.setDataType(DataType.STRING);
		a94.setName("c94");
		mm.getAttributes().add(a94);
		Attribute a95 = new Attribute();
		a95.setDataType(DataType.STRING);
		a95.setName("c95");
		mm.getAttributes().add(a95);
		Attribute a96 = new Attribute();
		a96.setDataType(DataType.STRING);
		a96.setName("c96");
		mm.getAttributes().add(a96);
		Attribute a97 = new Attribute();
		a97.setDataType(DataType.STRING);
		a97.setName("c97");
		mm.getAttributes().add(a97);
		Attribute a98 = new Attribute();
		a98.setDataType(DataType.STRING);
		a98.setName("c98");
		mm.getAttributes().add(a98);
		Attribute a99 = new Attribute();
		a99.setDataType(DataType.STRING);
		a99.setName("c99");
		mm.getAttributes().add(a99);
		Attribute a100 = new Attribute();
		a100.setDataType(DataType.STRING);
		a100.setName("c100");
		mm.getAttributes().add(a100);
		Attribute a101 = new Attribute();
		a101.setDataType(DataType.STRING);
		a101.setName("c101");
		mm.getAttributes().add(a101);
		Attribute a102 = new Attribute();
		a102.setDataType(DataType.STRING);
		a102.setName("c102");
		mm.getAttributes().add(a102);
		Attribute a103 = new Attribute();
		a103.setDataType(DataType.STRING);
		a103.setName("c103");
		mm.getAttributes().add(a103);
		Attribute a104 = new Attribute();
		a104.setDataType(DataType.STRING);
		a104.setName("c104");
		mm.getAttributes().add(a104);
		Attribute a105 = new Attribute();
		a105.setDataType(DataType.STRING);
		a105.setName("c105");
		mm.getAttributes().add(a105);
		Attribute a106 = new Attribute();
		a106.setDataType(DataType.STRING);
		a106.setName("c106");
		mm.getAttributes().add(a106);
		Attribute a107 = new Attribute();
		a107.setDataType(DataType.STRING);
		a107.setName("c107");
		mm.getAttributes().add(a107);
		Attribute a108 = new Attribute();
		a108.setDataType(DataType.STRING);
		a108.setName("c108");
		mm.getAttributes().add(a108);
		Attribute a109 = new Attribute();
		a109.setDataType(DataType.STRING);
		a109.setName("c109");
		mm.getAttributes().add(a109);
		Attribute a110 = new Attribute();
		a110.setDataType(DataType.STRING);
		a110.setName("c110");
		mm.getAttributes().add(a110);
		Attribute a111 = new Attribute();
		a111.setDataType(DataType.STRING);
		a111.setName("c111");
		mm.getAttributes().add(a111);
		Attribute a112 = new Attribute();
		a112.setDataType(DataType.STRING);
		a112.setName("c112");
		mm.getAttributes().add(a112);
		Attribute a113 = new Attribute();
		a113.setDataType(DataType.STRING);
		a113.setName("c113");
		mm.getAttributes().add(a113);
		Attribute a114 = new Attribute();
		a114.setDataType(DataType.STRING);
		a114.setName("c114");
		mm.getAttributes().add(a114);
		Attribute a115 = new Attribute();
		a115.setDataType(DataType.STRING);
		a115.setName("c115");
		mm.getAttributes().add(a115);
		Attribute a116 = new Attribute();
		a116.setDataType(DataType.STRING);
		a116.setName("c116");
		mm.getAttributes().add(a116);
		Attribute a117 = new Attribute();
		a117.setDataType(DataType.STRING);
		a117.setName("c117");
		mm.getAttributes().add(a117);
		Attribute a118 = new Attribute();
		a118.setDataType(DataType.STRING);
		a118.setName("c118");
		mm.getAttributes().add(a118);
		Attribute a119 = new Attribute();
		a119.setDataType(DataType.STRING);
		a119.setName("c119");
		mm.getAttributes().add(a119);
		Attribute a120 = new Attribute();
		a120.setDataType(DataType.STRING);
		a120.setName("c120");
		mm.getAttributes().add(a120);
		Attribute a121 = new Attribute();
		a121.setDataType(DataType.STRING);
		a121.setName("c121");
		mm.getAttributes().add(a121);
		Attribute a122 = new Attribute();
		a122.setDataType(DataType.STRING);
		a122.setName("c122");
		mm.getAttributes().add(a122);
		Attribute a123 = new Attribute();
		a123.setDataType(DataType.STRING);
		a123.setName("c123");
		mm.getAttributes().add(a123);
		Attribute a124 = new Attribute();
		a124.setDataType(DataType.STRING);
		a124.setName("c124");
		mm.getAttributes().add(a124);
		Attribute a125 = new Attribute();
		a125.setDataType(DataType.STRING);
		a125.setName("c125");
		mm.getAttributes().add(a125);
		Attribute a126 = new Attribute();
		a126.setDataType(DataType.STRING);
		a126.setName("c126");
		mm.getAttributes().add(a126);
		Attribute a127 = new Attribute();
		a127.setDataType(DataType.STRING);
		a127.setName("c127");
		mm.getAttributes().add(a127);
		Attribute a128 = new Attribute();
		a128.setDataType(DataType.STRING);
		a128.setName("c128");
		mm.getAttributes().add(a128);
		Attribute a129 = new Attribute();
		a129.setDataType(DataType.STRING);
		a129.setName("c129");
		mm.getAttributes().add(a129);
		Attribute a130 = new Attribute();
		a130.setDataType(DataType.STRING);
		a130.setName("c130");
		mm.getAttributes().add(a130);
		Attribute a131 = new Attribute();
		a131.setDataType(DataType.STRING);
		a131.setName("c131");
		mm.getAttributes().add(a131);
		Attribute a132 = new Attribute();
		a132.setDataType(DataType.STRING);
		a132.setName("c132");
		mm.getAttributes().add(a132);
		Attribute a133 = new Attribute();
		a133.setDataType(DataType.STRING);
		a133.setName("c133");
		mm.getAttributes().add(a133);
		Attribute a134 = new Attribute();
		a134.setDataType(DataType.STRING);
		a134.setName("c134");
		mm.getAttributes().add(a134);
		Attribute a135 = new Attribute();
		a135.setDataType(DataType.STRING);
		a135.setName("c135");
		mm.getAttributes().add(a135);
		Attribute a136 = new Attribute();
		a136.setDataType(DataType.STRING);
		a136.setName("c136");
		mm.getAttributes().add(a136);
		Attribute a137 = new Attribute();
		a137.setDataType(DataType.STRING);
		a137.setName("c137");
		mm.getAttributes().add(a137);
		Attribute a138 = new Attribute();
		a138.setDataType(DataType.STRING);
		a138.setName("c138");
		mm.getAttributes().add(a138);
		Attribute a139 = new Attribute();
		a139.setDataType(DataType.STRING);
		a139.setName("c139");
		mm.getAttributes().add(a139);
		Attribute a140 = new Attribute();
		a140.setDataType(DataType.STRING);
		a140.setName("c140");
		mm.getAttributes().add(a140);
		Attribute a141 = new Attribute();
		a141.setDataType(DataType.STRING);
		a141.setName("c141");
		mm.getAttributes().add(a141);
		Attribute a142 = new Attribute();
		a142.setDataType(DataType.STRING);
		a142.setName("c142");
		mm.getAttributes().add(a142);
		Attribute a143 = new Attribute();
		a143.setDataType(DataType.STRING);
		a143.setName("c143");
		mm.getAttributes().add(a143);
		Attribute a144 = new Attribute();
		a144.setDataType(DataType.STRING);
		a144.setName("c144");
		mm.getAttributes().add(a144);
		Attribute a145 = new Attribute();
		a145.setDataType(DataType.STRING);
		a145.setName("c145");
		mm.getAttributes().add(a145);
		Attribute a146 = new Attribute();
		a146.setDataType(DataType.STRING);
		a146.setName("c146");
		mm.getAttributes().add(a146);
		Attribute a147 = new Attribute();
		a147.setDataType(DataType.STRING);
		a147.setName("c147");
		mm.getAttributes().add(a147);
		Attribute a148 = new Attribute();
		a148.setDataType(DataType.STRING);
		a148.setName("c148");
		mm.getAttributes().add(a148);
		Attribute a149 = new Attribute();
		a149.setDataType(DataType.STRING);
		a149.setName("c149");
		mm.getAttributes().add(a149);
		Attribute a150 = new Attribute();
		a150.setDataType(DataType.STRING);
		a150.setName("c150");
		mm.getAttributes().add(a150);
		Attribute a151 = new Attribute();
		a151.setDataType(DataType.STRING);
		a151.setName("c151");
		mm.getAttributes().add(a151);
		Attribute a152 = new Attribute();
		a152.setDataType(DataType.STRING);
		a152.setName("c152");
		mm.getAttributes().add(a152);
		Attribute a153 = new Attribute();
		a153.setDataType(DataType.STRING);
		a153.setName("c153");
		mm.getAttributes().add(a153);
		Attribute a154 = new Attribute();
		a154.setDataType(DataType.STRING);
		a154.setName("c154");
		mm.getAttributes().add(a154);
		Attribute a155 = new Attribute();
		a155.setDataType(DataType.STRING);
		a155.setName("c155");
		mm.getAttributes().add(a155);
		Attribute a156 = new Attribute();
		a156.setDataType(DataType.STRING);
		a156.setName("c156");
		mm.getAttributes().add(a156);
		Attribute a157 = new Attribute();
		a157.setDataType(DataType.STRING);
		a157.setName("c157");
		mm.getAttributes().add(a157);
		Attribute a158 = new Attribute();
		a158.setDataType(DataType.STRING);
		a158.setName("c158");
		mm.getAttributes().add(a158);
		Attribute a159 = new Attribute();
		a159.setDataType(DataType.STRING);
		a159.setName("c159");
		mm.getAttributes().add(a159);
		Attribute a160 = new Attribute();
		a160.setDataType(DataType.STRING);
		a160.setName("c160");
		mm.getAttributes().add(a160);
		Attribute a161 = new Attribute();
		a161.setDataType(DataType.STRING);
		a161.setName("c161");
		mm.getAttributes().add(a161);
		Attribute a162 = new Attribute();
		a162.setDataType(DataType.STRING);
		a162.setName("c162");
		mm.getAttributes().add(a162);
		Attribute a163 = new Attribute();
		a163.setDataType(DataType.STRING);
		a163.setName("c163");
		mm.getAttributes().add(a163);
		Attribute a164 = new Attribute();
		a164.setDataType(DataType.STRING);
		a164.setName("c164");
		mm.getAttributes().add(a164);
		Attribute a165 = new Attribute();
		a165.setDataType(DataType.STRING);
		a165.setName("c165");
		mm.getAttributes().add(a165);
		Attribute a166 = new Attribute();
		a166.setDataType(DataType.STRING);
		a166.setName("c166");
		mm.getAttributes().add(a166);
		Attribute a167 = new Attribute();
		a167.setDataType(DataType.STRING);
		a167.setName("c167");
		mm.getAttributes().add(a167);

		thing.setMetaModel(mm);

		return thing;

	}

	public static Thing getThing2(String thingId) {

		Thing thing = new Thing();
		thing.setThingId(thingId);
		thing.getQos().setFrequency(100);

		Attribute c0 = new Attribute();
		c0.setDataType(DataType.STRING);
		c0.setName("c0");
		Attribute c1 = new Attribute();
		c1.setDataType(DataType.STRING);
		c1.setName("c1");
		Attribute c2 = new Attribute();
		c2.setDataType(DataType.STRING);
		c2.setName("c2");
		Attribute c3 = new Attribute();
		c3.setDataType(DataType.STRING);
		c3.setName("c3");
		Attribute c4 = new Attribute();
		c4.setDataType(DataType.STRING);
		c4.setName("c4");
		Attribute c5 = new Attribute();
		c5.setDataType(DataType.STRING);
		c5.setName("c5");
		Attribute c6 = new Attribute();
		c6.setDataType(DataType.STRING);
		c6.setName("c6");
		Attribute c7 = new Attribute();
		c7.setDataType(DataType.STRING);
		c7.setName("c7");
		Attribute c8 = new Attribute();
		c8.setDataType(DataType.STRING);
		c8.setName("c8");
		Attribute c9 = new Attribute();
		c9.setDataType(DataType.STRING);
		c9.setName("c9");
		Attribute c10 = new Attribute();
		c10.setDataType(DataType.STRING);
		c10.setName("c10");
		Attribute c11 = new Attribute();
		c11.setDataType(DataType.STRING);
		c11.setName("c11");
		Attribute c12 = new Attribute();
		c12.setDataType(DataType.STRING);
		c12.setName("c12");
		Attribute c13 = new Attribute();
		c13.setDataType(DataType.STRING);
		c13.setName("c13");
		Attribute c14 = new Attribute();
		c14.setDataType(DataType.STRING);
		c14.setName("c14");
		Attribute c15 = new Attribute();
		c15.setDataType(DataType.STRING);
		c15.setName("c15");
		Attribute c16 = new Attribute();
		c16.setDataType(DataType.STRING);
		c16.setName("c16");
		Attribute c17 = new Attribute();
		c17.setDataType(DataType.STRING);
		c17.setName("c17");
		Attribute c18 = new Attribute();
		c18.setDataType(DataType.STRING);
		c18.setName("c18");
		Attribute c19 = new Attribute();
		c19.setDataType(DataType.STRING);
		c19.setName("c19");
		Attribute c20 = new Attribute();
		c20.setDataType(DataType.STRING);
		c20.setName("c20");
		Attribute c21 = new Attribute();
		c21.setDataType(DataType.STRING);
		c21.setName("c21");
		Attribute c22 = new Attribute();
		c22.setDataType(DataType.STRING);
		c22.setName("c22");
		Attribute c23 = new Attribute();
		c23.setDataType(DataType.STRING);
		c23.setName("c23");

		MetaModel mm = new MetaModel();
		mm.getAttributes().add(c0);
		mm.getAttributes().add(c1);
		mm.getAttributes().add(c2);
		mm.getAttributes().add(c3);
		mm.getAttributes().add(c4);
		mm.getAttributes().add(c5);
		mm.getAttributes().add(c6);
		mm.getAttributes().add(c7);
		mm.getAttributes().add(c8);
		mm.getAttributes().add(c9);
		mm.getAttributes().add(c10);
		mm.getAttributes().add(c11);
		mm.getAttributes().add(c12);
		mm.getAttributes().add(c13);
		mm.getAttributes().add(c14);
		mm.getAttributes().add(c15);
		mm.getAttributes().add(c16);
		mm.getAttributes().add(c17);
		mm.getAttributes().add(c18);
		mm.getAttributes().add(c19);
		mm.getAttributes().add(c20);
		mm.getAttributes().add(c21);
		mm.getAttributes().add(c22);
		mm.getAttributes().add(c23);

		thing.setMetaModel(mm);

		return thing;

	}
}
