/*
 * Copyright (c) 2016. All rights reserved.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS".
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES.
 * 
 * Author: Florin Bogdan Balint
 * 
 */
package ac.at.tuwien.mt.client.internal;

/**
 * @author Florin Bogdan Balint
 *
 */
public enum Mode {

	AUTHENTICATE, //
	REGISTER_THING, REGISTER_THING_DIR, //
	GENERATE_DEMO_JSON_NATURAL_PERSON, GENERATE_DEMO_JSON_LEGAL_PERSON, GENERATE_THING_DEMO_JSON;

}
